// Generated by retool-db-types

export interface Tetris_leaderboard {
  id: number;
  name: string | null;
  score: number | null;
  timestamp: unknown;
}

export interface Property_management_system {
  id: number;
  property_name: string | null;
  address: string | null;
  owner_name: string | null;
  owner_contact: string | null;
  property_type: string | null;
  number_of_units: string | null;
  rental_price: string | null;
  availability_status: string | null;
  last_updated: string | null;
  photo: string | null;
}

export interface Warehouse_activities {
  id: number | null;
  type: string | null;
  delivery_id: string | null;
  parcel_id: string | null;
  date: string | null;
  status: string | null;
  description: string | null;
}

export interface Business_intelligence_dashboard {
  id: number;
  service_name: string | null;
  sales_volume: string | null;
  revenue: string | null;
  operating_expenses: string | null;
  net_income: string | null;
  gross_margin: string | null;
  customer_acquisition_cost: string | null;
  customer_lifetime_value: string | null;
  churn_rate: string | null;
  photo: string | null;
}

export interface Data_visualization_dashboard {
  id: number;
  store_name: string | null;
  location: string | null;
  revenue: string | null;
  number_of_employees: string | null;
  store_type: string | null;
  average_customer_rating: string | null;
  total_customers: string | null;
  opening_date: string | null;
  website: string | null;
  photo: string | null;
}

export interface __retool_vector_test_vector_05a79a98_4771_49a7_912c_2c06ccae4ee {
  id: number;
  embedding: unknown | null;
  content: string | null;
  source: string | null;
}

export interface Gpt_chat_sessions {
  id: number;
  text: string | null;
  created_at: unknown | null;
  owner: string | null;
}

export interface Gpt_chat_messages {
  id: number;
  session_id: number | null;
  prompt_response: string | null;
  is_prompt: boolean | null;
  metadata: Record<string, unknown> | null;
  created_at: unknown | null;
  from: string | null;
}

export interface Orders {
  id: number;
  user_id: number | null;
  status: string | null;
  created_at: unknown | null;
  updated_at: unknown | null;
  gift: boolean | null;
  charge_total: number | null;
  refund_total: number | null;
  credits_given: number | null;
  stripe_charge_id: string | null;
  complaint: string | null;
}

export interface __retool_vector_glb_inquiry_submissions_71ad18ed_26f2_4485_97f4 {
  id: number;
  embedding: unknown | null;
  content: string | null;
  source: string | null;
}

export interface Kpi_dashboard {
  id: number;
  campaign_name: string | null;
  campaign_owner: string | null;
  start_date: string | null;
  end_date: string | null;
  budget: string | null;
  impressions: string | null;
  clicks: string | null;
  conversions: string | null;
  revenue: string | null;
  photo: string | null;
}

export interface Elegancia_submissions {
  id: string;
  event_name: string | null;
  created_date: unknown | null;
  desired_date: string | null;
  event_type: string | null;
  email: string | null;
  desired_time: string | null;
  desired_space: string | null;
  phone: string | null;
  additional_details: string | null;
  full_name: string | null;
  status: unknown | null;
  reviewed: boolean | null;
  archive: boolean | null;
  head_count: number | null;
}

export interface Buen_table {
  id: number;
  created_date: unknown;
  value: string | null;
}

export interface __retool_vector_bad_coffee_shops_06f52c66_0142_482c_bea1_fa8270 {
  id: number;
  embedding: unknown | null;
  content: string | null;
  source: string | null;
}

export interface __retool_vector_glb_data_42ae9372_bb22_4abe_8c7c_7fe9b09bb756 {
  id: number;
  embedding: unknown | null;
  content: string | null;
  source: string | null;
}

export interface __retool_vector_glb_submissions_b80574c0_2ea4_4b0f_b750_a745843 {
  id: number;
  embedding: unknown | null;
  content: string | null;
  source: string | null;
}

export interface __retool_vector_john_design_site_5bce5e49_2f4e_41f1_b36e_fc7fd3 {
  id: number;
  embedding: unknown | null;
  content: string | null;
  source: string | null;
}

export interface __retool_vector_top_coffee_shops_dfe6ef85_d189_4706_8d7f_ea6c70 {
  id: number;
  embedding: unknown | null;
  content: string | null;
  source: string | null;
}

export interface Coffee_db {
  alias: string;
  aiScore: number | null;
  aiNotes: string | null;
  id: string;
  name: string;
  image_url: string | null;
  is_closed: boolean | null;
  url: string | null;
  review_count: number | null;
  title: string | null;
}

export interface Db_test {
  id: number;
  name: string | null;
  email: string | null;
}

export interface Glb_customer_notes {
  id: number;
  email: string | null;
  note: string | null;
}

export interface Glb_submissions {
  id: string;
  event_name: string | null;
  created_date: unknown | null;
  event_type: string | null;
  full_name: string | null;
  email: string | null;
  phone: string | null;
  desired_date: string | null;
  desired_time: string | null;
  desired_space: string | null;
  additional_details: string | null;
  reviewed: boolean | null;
  archive: boolean | null;
  status: unknown | null;
  head_count: number | null;
}

export interface Test_submissions {
  id: number;
  event_name: string | null;
  created_date: unknown | null;
  event_type: string | null;
  full_name: string | null;
  email: string | null;
  phone: string | null;
  desired_date: string | null;
  desired_time: string | null;
  desired_space: string | null;
  additional_details: string | null;
  head_count: number | null;
}

export interface Unshipped_orders {
  id: number;
  status: string | null;
  created_at: unknown | null;
  charge_total: number | null;
}

export interface Users {
  id: number;
  name: string | null;
  email: string | null;
  signup_date: unknown | null;
  role: string | null;
  enabled: boolean | null;
}

export interface Coffee_app_dev {
  id: string;
  audience: string | null;
  confirmation_sent_at: unknown | null;
  confirmed_at: unknown | null;
  created_at: unknown | null;
  email: string | null;
  role: string | null;
  updated_at: unknown | null;
  url: string | null;
  user_metadata: Record<string, unknown> | null;
}

export interface StilleVisQuestionaire {
  missionStatement: string | null;
  differentiationFromCompetitors: string | null;
  secondaryAudience: string | null;
  companyHistory: string | null;
  keyMessages: string | null;
  typographyPreferences: string | null;
  primaryAudience: string | null;
  preferencesAndAversions: string | null;
  colorPreferences: string | null;
  brandPersonality: string | null;
  visualInspiration: string | null;
  mainCompetitors: string | null;
  stakeholders: string | null;
  textInput1: string | null;
  fileDropzone1: Record<string, unknown> | null;
  id: number;
  fileDropzone2: Record<string, unknown> | null;
}

export interface Sample_users {
  id: number;
  name: string | null;
  email: string | null;
  signup_date: unknown | null;
  role: string | null;
  enabled: boolean | null;
}

export interface Mobile_app_sample_data {
  id: number;
  name: string | null;
  email: string | null;
  sales: number | null;
  image: string | null;
}

